export const path_name = {
  dashboard: '/dashboard',          
  user: '/tai-khoan',              
  building: '/toa-nha',             
  room: '/phong',                   
  tenant: '/khach-thue',            
  contract: '/hop-dong',            
  invoice: '/hoa-don',              
  payment: '/thanh-toan',           
  issue: '/su-co',                  
  notification: '/thong-bao',  
   meter: "/dien-nuoc",
  service: "/dich-vu",
  amenity: "/tien-nghi",
  setting: "/settings",
  login:"dang-nhap",   
};
